"""
SQLAlchemy database model for Frame

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/database/models/class_name.py.j2 instead.
"""

import uuid
import uuid6
import datetime
from typing import TYPE_CHECKING

from platformics.database.models.base import Base
from sqlalchemy import ForeignKey, String, Float, Integer, Enum, Boolean, DateTime
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func
from platformics.database.models.file import File

if TYPE_CHECKING:
    from platformics.database.models.file import File
    from database.models.deposition import Deposition
    from database.models.run import Run
    from database.models.per_section_parameters import PerSectionParameters

    ...
else:
    File = "File"
    Deposition = "Deposition"
    Run = "Run"
    PerSectionParameters = "PerSectionParameters"
    ...


class Frame(Base):
    __tablename__ = "frame"
    __mapper_args__ = {"polymorphic_identity": __tablename__, "polymorphic_load": "inline"}

    deposition_id: Mapped[int] = mapped_column(Integer, ForeignKey("deposition.id"), nullable=False, index=True)
    deposition: Mapped["Deposition"] = relationship(
        "Deposition",
        foreign_keys=deposition_id,
        back_populates="frames",
    )
    run_id: Mapped[int] = mapped_column(Integer, ForeignKey("run.id"), nullable=False, index=True)
    run: Mapped["Run"] = relationship(
        "Run",
        foreign_keys=run_id,
        back_populates="frames",
    )
    acquisition_order: Mapped[int] = mapped_column(Integer, nullable=True)
    accumulated_dose: Mapped[float] = mapped_column(Float, nullable=True)
    exposure_dose: Mapped[float] = mapped_column(Float, nullable=True)
    is_gain_corrected: Mapped[bool] = mapped_column(Boolean, nullable=True)
    per_section_parameters: Mapped[list[PerSectionParameters]] = relationship(
        "PerSectionParameters",
        back_populates="frame",
        uselist=True,
        foreign_keys="PerSectionParameters.frame_id",
        cascade="all, delete-orphan",
    )
    s3_frame_path: Mapped[str] = mapped_column(String, nullable=True)
    https_frame_path: Mapped[str] = mapped_column(String, nullable=True)
    file_size: Mapped[float] = mapped_column(Float, nullable=True)
    id: Mapped[int] = mapped_column(Integer, nullable=False, index=True, autoincrement=True, primary_key=True)
