"""
SQLAlchemy database model for Frame

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/database/models/class_name.py.j2 instead.
"""

from typing import TYPE_CHECKING

from sqlalchemy import BigInteger, Boolean, Float, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from platformics.database.models.base import Base
from platformics.database.models.file import File

if TYPE_CHECKING:
    from database.models.deposition import Deposition
    from database.models.run import Run

    from platformics.database.models.file import File

    ...
else:
    File = "File"
    Deposition = "Deposition"
    Run = "Run"
    ...


class Frame(Base):
    __tablename__ = "frame"
    __mapper_args__ = {"polymorphic_identity": __tablename__, "polymorphic_load": "inline"}

    deposition_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("deposition.id"), nullable=False, index=True)
    deposition: Mapped["Deposition"] = relationship(
        "Deposition",
        foreign_keys=deposition_id,
        back_populates="frames",
    )
    run_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("run.id"), nullable=False, index=True)
    run: Mapped["Run"] = relationship(
        "Run",
        foreign_keys=run_id,
        back_populates="frames",
    )
    raw_angle: Mapped[float] = mapped_column(Float, nullable=True)
    acquisition_order: Mapped[int] = mapped_column(BigInteger, nullable=True)
    dose: Mapped[float] = mapped_column(Float, nullable=True)
    is_gain_corrected: Mapped[bool] = mapped_column(Boolean, nullable=True)
    s3_frame_path: Mapped[str] = mapped_column(String, nullable=False)
    https_frame_path: Mapped[str] = mapped_column(String, nullable=False)
    file_size: Mapped[int] = mapped_column(BigInteger, nullable=True)
    id: Mapped[int] = mapped_column(BigInteger, nullable=False, index=True, autoincrement=True, primary_key=True)
