"""
SQLAlchemy database model for PerSectionAlignmentParameters

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/database/models/class_name.py.j2 instead.
"""

from typing import TYPE_CHECKING

from platformics.database.models.base import Base
from platformics.database.models.file import File
from sqlalchemy import Float, ForeignKey, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship

if TYPE_CHECKING:
    from database.models.alignment import Alignment
    from platformics.database.models.file import File

    ...
else:
    File = "File"
    Alignment = "Alignment"
    ...


class PerSectionAlignmentParameters(Base):
    __tablename__ = "per_section_alignment_parameters"
    __mapper_args__ = {"polymorphic_identity": __tablename__, "polymorphic_load": "inline"}

    alignment_id: Mapped[int] = mapped_column(Integer, ForeignKey("alignment.id"), nullable=False, index=True)
    alignment: Mapped["Alignment"] = relationship(
        "Alignment",
        foreign_keys=alignment_id,
        back_populates="per_section_alignments",
    )
    z_index: Mapped[int] = mapped_column(Integer, nullable=False)
    x_offset: Mapped[float] = mapped_column(Float, nullable=True)
    y_offset: Mapped[float] = mapped_column(Float, nullable=True)
    in_plane_rotation: Mapped[float] = mapped_column(Float, nullable=True)
    beam_tilt: Mapped[float] = mapped_column(Float, nullable=True)
    tilt_angle: Mapped[float] = mapped_column(Float, nullable=True)
    id: Mapped[int] = mapped_column(Integer, nullable=False, index=True, autoincrement=True, primary_key=True)
