"""
Auto-generated by running `make codegen`. Do not edit!
Make changes to the template platformics/codegen/templates/database/models/class_name.py.j2 instead.

SQLAlchemy database model for PerSectionParameters
"""

from typing import TYPE_CHECKING

from platformics.database.models.base import Base
from sqlalchemy import Float, ForeignKey, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship

if TYPE_CHECKING:
    from database.models.frame import Frame
    from database.models.run import Run
    from database.models.tiltseries import Tiltseries

    ...
else:
    Frame = "Frame"
    Run = "Run"
    Tiltseries = "Tiltseries"
    ...


class PerSectionParameters(Base):
    __tablename__ = "per_section_parameters"
    __mapper_args__ = {"polymorphic_identity": __tablename__, "polymorphic_load": "inline"}

    astigmatic_angle: Mapped[float] = mapped_column(Float, nullable=True)
    frame_id: Mapped[int] = mapped_column(Integer, ForeignKey("frame.id"), nullable=False, index=True)
    frame: Mapped["Frame"] = relationship(
        "Frame",
        foreign_keys=frame_id,
        back_populates="per_section_parameters",
    )
    major_defocus: Mapped[float] = mapped_column(Float, nullable=True)
    max_resolution: Mapped[float] = mapped_column(Float, nullable=True)
    minor_defocus: Mapped[float] = mapped_column(Float, nullable=True)
    phase_shift: Mapped[float] = mapped_column(Float, nullable=True)
    raw_angle: Mapped[float] = mapped_column(Float, nullable=False)
    run_id: Mapped[int] = mapped_column(Integer, ForeignKey("run.id"), nullable=False, index=True)
    run: Mapped["Run"] = relationship(
        "Run",
        foreign_keys=run_id,
        back_populates="per_section_parameters",
    )
    tiltseries_id: Mapped[int] = mapped_column(Integer, ForeignKey("tiltseries.id"), nullable=False, index=True)
    tiltseries: Mapped["Tiltseries"] = relationship(
        "Tiltseries",
        foreign_keys=tiltseries_id,
        back_populates="per_section_parameters",
    )
    z_index: Mapped[int] = mapped_column(Integer, nullable=False)
    id: Mapped[int] = mapped_column(Integer, nullable=False, index=True, autoincrement=True, primary_key=True)
