"""autogenerated

Create Date: 2024-08-07 20:58:05.979523

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240807_165802"
down_revision = "20240807_164544"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tiltseries", sa.Column("spherical_aberration_constant", sa.Float(), nullable=False))
    op.drop_column("tiltseries", "spherical_abberation_constant")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tiltseries",
        sa.Column(
            "spherical_abberation_constant", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("tiltseries", "spherical_aberration_constant")
    # ### end Alembic commands ###
