"""autogenerated

Create Date: 2024-08-07 20:13:57.051465

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240807_161352"
down_revision = "20240807_122907"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dataset",
        sa.Column(
            "sample_type",
            sa.Enum(
                "cell",
                "tissue",
                "organism",
                "organelle",
                "virus",
                "in_vitro",
                "in_silico",
                "other",
                name="sample_type_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset", "sample_type")
    # ### end Alembic commands ###
