"""autogenerated

Create Date: 2024-08-29 02:43:25.938941

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20240828_194323'
down_revision = '20240828_110410'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alignment', sa.Column('x_rotation_offset', sa.Float(), nullable=True))
    op.add_column('alignment', sa.Column('affine_transformation_matrix', sa.String(), nullable=True))
    op.drop_column('alignment', 'volume_x_rotation')
    op.drop_column('alignment', 'alignment')
    op.drop_column('tomogram', 'affine_transformation_matrix')
    op.drop_column('tomogram', 'tomogram_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tomogram', sa.Column('tomogram_type', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.add_column('tomogram', sa.Column('affine_transformation_matrix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alignment', sa.Column('alignment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('alignment', sa.Column('volume_x_rotation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('alignment', 'affine_transformation_matrix')
    op.drop_column('alignment', 'x_rotation_offset')
    # ### end Alembic commands ###
