"""autogenerated

Create Date: 2024-08-28 15:04:13.772132

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240828_110410"
down_revision = "20240807_181540"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset", "dataset_citations")
    op.drop_column("dataset", "related_database_links")
    op.drop_column("deposition", "dataset_citations")
    op.drop_column("deposition", "related_database_links")
    op.add_column("tiltseries", sa.Column("s3_mrc_file", sa.String(), nullable=True))
    op.add_column("tiltseries", sa.Column("https_mrc_file", sa.String(), nullable=True))
    op.drop_column("tiltseries", "https_mrc_bin1")
    op.drop_column("tiltseries", "s3_mrc_bin1")
    op.add_column("tomogram", sa.Column("s3_mrc_file", sa.String(), nullable=True))
    op.add_column("tomogram", sa.Column("https_mrc_file", sa.String(), nullable=True))
    op.drop_column("tomogram", "s3_mrc_scale0")
    op.drop_column("tomogram", "https_mrc_scale0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tomogram", sa.Column("https_mrc_scale0", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("tomogram", sa.Column("s3_mrc_scale0", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("tomogram", "https_mrc_file")
    op.drop_column("tomogram", "s3_mrc_file")
    op.add_column("tiltseries", sa.Column("s3_mrc_bin1", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("tiltseries", sa.Column("https_mrc_bin1", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("tiltseries", "https_mrc_file")
    op.drop_column("tiltseries", "s3_mrc_file")
    op.add_column("deposition", sa.Column("related_database_links", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("deposition", sa.Column("dataset_citations", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("dataset", sa.Column("related_database_links", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("dataset", sa.Column("dataset_citations", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
