"""autogenerated

Create Date: 2024-10-10 17:50:56.183502

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20241010_135050'
down_revision = '20241008_125739'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frame', 'deposition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('frame', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('frame', 'raw_angle',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('frame', 'dose',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('gain_file', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gain_file', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('frame', 'dose',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('frame', 'raw_angle',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('frame', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('frame', 'deposition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
