"""autogenerated

Create Date: 2024-08-07 20:26:48.658021

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240807_162645"
down_revision = "20240807_162546"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tomogram", sa.Column("reconstruction_software", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tomogram", "reconstruction_software")
    # ### end Alembic commands ###
