"""autogenerated

Create Date: 2024-08-07 20:24:53.932676

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240807_162450"
down_revision = "20240807_162327"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tomogram", sa.Column("tomogram_processing_software", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tomogram", "tomogram_processing_software")
    # ### end Alembic commands ###
