"""autogenerated

Create Date: 2025-07-24 19:35:33.544212

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20250724_123531'
down_revision = '20250722_205427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'sample_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('cell', 'cell_line', 'in_silico', 'in_vitro', 'organelle', 'organism', 'organoid', 'other', 'primary_cell_culture', 'tissue', 'virus', name='sample_type_enum', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'sample_type',
               existing_type=sa.Enum('cell', 'cell_line', 'in_silico', 'in_vitro', 'organelle', 'organism', 'organoid', 'other', 'primary_cell_culture', 'tissue', 'virus', name='sample_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    # ### end Alembic commands ###
