"""autogenerated

Create Date: 2025-01-09 16:43:14.268438

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20250109_114311"
down_revision = "20241213_131118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("annotation_file", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("dataset", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("frame", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("tiltseries", sa.Column("file_size_omezarr", sa.Integer(), nullable=True))
    op.add_column("tiltseries", sa.Column("file_size_mrc", sa.Integer(), nullable=True))
    op.add_column("tomogram", sa.Column("file_size_omezarr", sa.Integer(), nullable=True))
    op.add_column("tomogram", sa.Column("file_size_mrc", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tomogram", "file_size_mrc")
    op.drop_column("tomogram", "file_size_omezarr")
    op.drop_column("tiltseries", "file_size_mrc")
    op.drop_column("tiltseries", "file_size_omezarr")
    op.drop_column("frame", "file_size")
    op.drop_column("dataset", "file_size")
    op.drop_column("annotation_file", "file_size")
    # ### end Alembic commands ###
