"""autogenerated

Create Date: 2025-03-13 21:24:19.258299

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20250313_142410'
down_revision = '20250219_052826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('per_section_parameters',
    sa.Column('astigmatic_angle', sa.Float(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('major_defocus', sa.Float(), nullable=True),
    sa.Column('max_resolution', sa.Float(), nullable=True),
    sa.Column('minor_defocus', sa.Float(), nullable=True),
    sa.Column('phase_shift', sa.Float(), nullable=True),
    sa.Column('raw_angle', sa.Float(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tiltseries_id', sa.Integer(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], name=op.f('fk_per_section_parameters_frame_id_frame')),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], name=op.f('fk_per_section_parameters_run_id_run')),
    sa.ForeignKeyConstraint(['tiltseries_id'], ['tiltseries.id'], name=op.f('fk_per_section_parameters_tiltseries_id_tiltseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_per_section_parameters')),
    )
    op.create_index(op.f('ix_per_section_parameters_frame_id'), 'per_section_parameters', ['frame_id'], unique=False)
    op.create_index(op.f('ix_per_section_parameters_id'), 'per_section_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_per_section_parameters_run_id'), 'per_section_parameters', ['run_id'], unique=False)
    op.create_index(op.f('ix_per_section_parameters_tiltseries_id'), 'per_section_parameters', ['tiltseries_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_per_section_parameters_tiltseries_id'), table_name='per_section_parameters')
    op.drop_index(op.f('ix_per_section_parameters_run_id'), table_name='per_section_parameters')
    op.drop_index(op.f('ix_per_section_parameters_id'), table_name='per_section_parameters')
    op.drop_index(op.f('ix_per_section_parameters_frame_id'), table_name='per_section_parameters')
    op.drop_table('per_section_parameters')
    # ### end Alembic commands ###
