"""autogenerated

Create Date: 2025-08-19 15:15:14.066135

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20250819_111511'
down_revision = '20250724_123531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identified_object',
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('object_description', sa.String(), nullable=True),
    sa.Column('object_state', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], name=op.f('fk_identified_object_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identified_object'))
    )
    op.create_index(op.f('ix_identified_object_id'), 'identified_object', ['id'], unique=False)
    op.create_index(op.f('ix_identified_object_run_id'), 'identified_object', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identified_object_run_id'), table_name='identified_object')
    op.drop_index(op.f('ix_identified_object_id'), table_name='identified_object')
    op.drop_table('identified_object')
    # ### end Alembic commands ###