"""autogenerated

Create Date: 2025-10-28 14:24:13.316629

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20251028_082407"
down_revision = "20250819_111511"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "annotation_shape",
        "shape_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "SegmentationMask",
            "OrientedPoint",
            "Point",
            "InstanceSegmentation",
            "InstanceSegmentationMask",
            "Mesh",
            name="annotation_file_shape_type_enum",
            native_enum=False,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "annotation_shape",
        "shape_type",
        existing_type=sa.Enum(
            "SegmentationMask",
            "OrientedPoint",
            "Point",
            "InstanceSegmentation",
            "InstanceSegmentationMask",
            "Mesh",
            name="annotation_file_shape_type_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
