"""autogenerated

Create Date: 2026-03-07 00:08:42.068815

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20260306_160839"
down_revision = "20260306_145132"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE annotation SET annotation_ingest_id = '' WHERE annotation_ingest_id IS NULL")
    op.alter_column("annotation", "annotation_ingest_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("annotation", "annotation_ingest_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
