"""autogenerated

Create Date: 2026-05-06 04:57:23.131016

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20260505_215721'
down_revision = '20260330_113611'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('per_section_parameters', 'frame_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('per_section_parameters', 'frame_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
