"""autogenerated

Create Date: 2026-05-04 18:50:27.070165

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "20260504_115025"
down_revision = "20260330_113611"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Remove duplicate rows before adding the unique constraint, keeping the lowest id per (run_id, object_id).
    op.execute(
        """
        DELETE FROM identified_object
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM identified_object
            GROUP BY run_id, object_id
        )
        """,
    )
    op.create_unique_constraint("uq_identified_object_run_id_object_id", "identified_object", ["run_id", "object_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_identified_object_run_id_object_id", "identified_object", type_="unique")
    # ### end Alembic commands ###
