"""autogenerated

Create Date: 2026-01-22 19:41:42.173885

"""

# revision identifiers, used by Alembic.
revision = '20260122_114123'
down_revision = '20250819_111511'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
