# TODO: include non-validation documentation / attributes in this and dataset_config.yaml

name: cdp-dataset-config-validate
id: cdp-dataset-config-validate
version: 1.1.0
description: Validate dataset configs
imports:
- linkml:types
- ./dataset_config
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/

# For the sources only attributes, refine the types of sources that exist

classes:
  Container:
    tree_root: true
    attributes: 
      annotations:
        multivalued: true
        range: AnnotationEntity
      dataset_keyphotos:
        multivalued: true
        range: DatasetKeyPhotoEntity
      datasets:
        multivalued: true
        range: DatasetEntity
      frames:
        multivalued: true
        range: FrameEntity
      gains:
        multivalued: true
        range: GainEntity
      key_images:
        multivalued: true
        range: KeyImageEntity
      rawtilts:
        multivalued: true
        range: RawTiltEntity
      runs:
        multivalued: true
        range: RunEntity
      standardization_config:
        range: StandardizationConfig
      tiltseries:
        multivalued: true
        range: TiltSeriesEntity
      tomograms:
        multivalued: true
        range: TomogramEntity
      voxel_spacings:
        multivalued: true
        range: VoxelSpacingEntity
    
source_file: ../../schema/v1.1.0/metadata