"""
Factory for generating PerSectionParameters objects.

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/test_infra/factories/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long

import factory
from database.models import PerSectionParameters
from factory import Faker, fuzzy
from faker_biology.bioseq import Bioseq
from faker_biology.physiology import Organ
from faker_enum import EnumProvider

from platformics.test_infra.factories.base import CommonFactory
from test_infra.factories.frame import FrameFactory
from test_infra.factories.run import RunFactory
from test_infra.factories.tiltseries import TiltseriesFactory

Faker.add_provider(Bioseq)
Faker.add_provider(Organ)
Faker.add_provider(EnumProvider)


class PerSectionParametersFactory(CommonFactory):
    class Meta:
        sqlalchemy_session = None  # workaround for a bug in factoryboy
        model = PerSectionParameters

        sqlalchemy_get_or_create = ("id",)


    astigmatic_angle = fuzzy.FuzzyFloat(1, 100)
    frame = factory.SubFactory(
        FrameFactory,
    )
    major_defocus = fuzzy.FuzzyFloat(1, 100)
    max_resolution = fuzzy.FuzzyFloat(1, 100)
    minor_defocus = fuzzy.FuzzyFloat(1, 100)
    phase_shift = fuzzy.FuzzyFloat(1, 100)
    raw_angle = fuzzy.FuzzyFloat(1, 100)
    run = factory.SubFactory(
        RunFactory,
    )
    tiltseries = factory.SubFactory(
        TiltseriesFactory,
    )

    z_index = fuzzy.FuzzyInteger(1, 1000)


    # Auto increment integer identifiers starting with 1
    id = factory.Sequence(lambda n: n + 1)
