"""
GraphQL type for AnnotationMethodLink

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/graphql_api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import datetime
import enum
import typing
from typing import TYPE_CHECKING, Annotated, Optional, Sequence

import database.models as db
import strawberry
from fastapi import Depends
from graphql_api.helpers.annotation_method_link import (
    AnnotationMethodLinkGroupByOptions,
    build_annotation_method_link_groupby_output,
)
from sqlalchemy import inspect
from sqlalchemy.engine.row import RowMapping
from sqlalchemy.ext.asyncio import AsyncSession
from strawberry.types import Info
from support.enums import annotation_method_link_type_enum
from support.limit_offset import LimitOffsetClause
from typing_extensions import TypedDict
from validators.annotation_method_link import (
    AnnotationMethodLinkCreateInputValidator,
    AnnotationMethodLinkUpdateInputValidator,
)

from platformics.graphql_api.core.deps import get_authz_client, get_db_session, is_system_user, require_auth_principal
from platformics.graphql_api.core.errors import PlatformicsError
from platformics.graphql_api.core.query_builder import get_aggregate_db_rows, get_db_rows
from platformics.graphql_api.core.query_input_types import (
    EnumComparators,
    IntComparators,
    StrComparators,
    aggregator_map,
    orderBy,
)
from platformics.graphql_api.core.relay_interface import EntityInterface
from platformics.graphql_api.core.strawberry_extensions import DependencyExtension
from platformics.security.authorization import AuthzAction, AuthzClient, Principal

E = typing.TypeVar("E")
T = typing.TypeVar("T")

if TYPE_CHECKING:
    from graphql_api.types.annotation import (
        Annotation,
        AnnotationAggregateWhereClause,
        AnnotationOrderByClause,
        AnnotationWhereClause,
    )

    pass
else:
    AnnotationWhereClause = "AnnotationWhereClause"
    AnnotationAggregateWhereClause = "AnnotationAggregateWhereClause"
    Annotation = "Annotation"
    AnnotationOrderByClause = "AnnotationOrderByClause"
    pass


"""
------------------------------------------------------------------------------
Dataloaders
------------------------------------------------------------------------------
These are batching functions for loading related objects to avoid N+1 queries.
"""


@strawberry.field
async def load_annotation_rows(
    root: "AnnotationMethodLink",
    info: Info,
    where: Annotated["AnnotationWhereClause", strawberry.lazy("graphql_api.types.annotation")] | None = None,
    order_by: Optional[
        list[Annotated["AnnotationOrderByClause", strawberry.lazy("graphql_api.types.annotation")]]
    ] = [],
) -> Optional[Annotated["Annotation", strawberry.lazy("graphql_api.types.annotation")]]:
    dataloader = info.context["sqlalchemy_loader"]
    mapper = inspect(db.AnnotationMethodLink)
    relationship = mapper.relationships["annotation"]
    return await dataloader.loader_for(relationship, where, order_by).load(root.annotation_id)  # type:ignore


"""
------------------------------------------------------------------------------
Define Strawberry GQL types
------------------------------------------------------------------------------
"""


"""
Only let users specify IDs in WHERE clause when mutating data (for safety).
We can extend that list as we gather more use cases from the FE team.
"""


@strawberry.input
class AnnotationMethodLinkWhereClauseMutations(TypedDict):
    id: IntComparators | None


"""
Supported WHERE clause attributes
"""


@strawberry.input
class AnnotationMethodLinkWhereClause(TypedDict):
    annotation: Optional[Annotated["AnnotationWhereClause", strawberry.lazy("graphql_api.types.annotation")]] | None
    annotation_id: Optional[IntComparators] | None
    link_type: Optional[EnumComparators[annotation_method_link_type_enum]] | None
    name: Optional[StrComparators] | None
    link: Optional[StrComparators] | None
    id: Optional[IntComparators] | None


"""
Supported ORDER BY clause attributes
"""


@strawberry.input
class AnnotationMethodLinkOrderByClause(TypedDict):
    annotation: Optional[Annotated["AnnotationOrderByClause", strawberry.lazy("graphql_api.types.annotation")]] | None
    link_type: Optional[orderBy] | None
    name: Optional[orderBy] | None
    link: Optional[orderBy] | None
    id: Optional[orderBy] | None


"""
Define AnnotationMethodLink type
"""


@strawberry.type(
    description="A set of links to models, source code, documentation, etc referenced by annotation method",
)
class AnnotationMethodLink(EntityInterface):
    annotation: Optional[Annotated["Annotation", strawberry.lazy("graphql_api.types.annotation")]] = (
        load_annotation_rows
    )  # type:ignore
    annotation_id: Optional[int]
    link_type: annotation_method_link_type_enum = strawberry.field(
        description="Type of link (e.g. model, source code, documentation)",
    )
    name: Optional[str] = strawberry.field(description="user readable name of the resource", default=None)
    link: str = strawberry.field(description="URL to the resource")
    id: int = strawberry.field(description="Numeric identifier (May change!)")


"""
We need to add this to each Queryable type so that strawberry will accept either our
Strawberry type *or* a SQLAlchemy model instance as a valid response class from a resolver
"""
AnnotationMethodLink.__strawberry_definition__.is_type_of = (  # type: ignore
    lambda obj, info: type(obj) == db.AnnotationMethodLink or type(obj) == AnnotationMethodLink
)

"""
------------------------------------------------------------------------------
Aggregation types
------------------------------------------------------------------------------
"""
"""
Define columns that support numerical aggregations
"""


@strawberry.type
class AnnotationMethodLinkNumericalColumns:
    id: Optional[int] = None


"""
Define columns that support min/max aggregations
"""


@strawberry.type
class AnnotationMethodLinkMinMaxColumns:
    name: Optional[str] = None
    link: Optional[str] = None
    id: Optional[int] = None


"""
Define enum of all columns to support count and count(distinct) aggregations
"""


@strawberry.enum
class AnnotationMethodLinkCountColumns(enum.Enum):
    linkType = "link_type"
    name = "name"
    link = "link"
    id = "id"


"""
Support *filtering* on aggregates and related aggregates
"""


@strawberry.input
class AnnotationMethodLinkAggregateWhereClauseCount(TypedDict):
    arguments: Optional["AnnotationMethodLinkCountColumns"] | None
    distinct: Optional[bool] | None
    filter: Optional[AnnotationMethodLinkWhereClause] | None
    predicate: Optional[IntComparators] | None


@strawberry.input
class AnnotationMethodLinkAggregateWhereClause(TypedDict):
    count: AnnotationMethodLinkAggregateWhereClauseCount


"""
All supported aggregation functions
"""


@strawberry.type
class AnnotationMethodLinkAggregateFunctions:
    # This is a hack to accept "distinct" and "columns" as arguments to "count"
    @strawberry.field
    def count(
        self, distinct: Optional[bool] = False, columns: Optional[AnnotationMethodLinkCountColumns] = None,
    ) -> Optional[int]:
        # Count gets set with the proper value in the resolver, so we just return it here
        return self.count  # type: ignore

    sum: Optional[AnnotationMethodLinkNumericalColumns] = None
    avg: Optional[AnnotationMethodLinkNumericalColumns] = None
    stddev: Optional[AnnotationMethodLinkNumericalColumns] = None
    variance: Optional[AnnotationMethodLinkNumericalColumns] = None
    min: Optional[AnnotationMethodLinkMinMaxColumns] = None
    max: Optional[AnnotationMethodLinkMinMaxColumns] = None
    groupBy: Optional[AnnotationMethodLinkGroupByOptions] = None


"""
Wrapper around AnnotationMethodLinkAggregateFunctions
"""


@strawberry.type
class AnnotationMethodLinkAggregate:
    aggregate: Optional[list[AnnotationMethodLinkAggregateFunctions]] = None


"""
------------------------------------------------------------------------------
Mutation types
------------------------------------------------------------------------------
"""


@strawberry.input()
class AnnotationMethodLinkCreateInput:
    annotation_id: Optional[strawberry.ID] = strawberry.field(
        description="Reference to annotation this link applies to", default=None,
    )
    link_type: annotation_method_link_type_enum = strawberry.field(
        description="Type of link (e.g. model, source code, documentation)",
    )
    name: Optional[str] = strawberry.field(description="user readable name of the resource", default=None)
    link: str = strawberry.field(description="URL to the resource")
    id: int = strawberry.field(description="Numeric identifier (May change!)")


@strawberry.input()
class AnnotationMethodLinkUpdateInput:
    annotation_id: Optional[strawberry.ID] = strawberry.field(
        description="Reference to annotation this link applies to", default=None,
    )
    link_type: Optional[annotation_method_link_type_enum] = strawberry.field(
        description="Type of link (e.g. model, source code, documentation)",
    )
    name: Optional[str] = strawberry.field(description="user readable name of the resource", default=None)
    link: Optional[str] = strawberry.field(description="URL to the resource")
    id: Optional[int] = strawberry.field(description="Numeric identifier (May change!)")


"""
------------------------------------------------------------------------------
Utilities
------------------------------------------------------------------------------
"""


@strawberry.field(extensions=[DependencyExtension()])
async def resolve_annotation_method_links(
    session: AsyncSession = Depends(get_db_session, use_cache=False),
    authz_client: AuthzClient = Depends(get_authz_client),
    principal: Principal = Depends(require_auth_principal),
    where: Optional[AnnotationMethodLinkWhereClause] = None,
    order_by: Optional[list[AnnotationMethodLinkOrderByClause]] = [],
    limit_offset: Optional[LimitOffsetClause] = None,
) -> typing.Sequence[AnnotationMethodLink]:
    """
    Resolve AnnotationMethodLink objects. Used for queries (see graphql_api/queries.py).
    """
    limit = limit_offset["limit"] if limit_offset and "limit" in limit_offset else None
    offset = limit_offset["offset"] if limit_offset and "offset" in limit_offset else None
    if offset and not limit:
        raise PlatformicsError("Cannot use offset without limit")
    return await get_db_rows(db.AnnotationMethodLink, session, authz_client, principal, where, order_by, AuthzAction.VIEW, limit, offset)  # type: ignore


def format_annotation_method_link_aggregate_output(
    query_results: Sequence[RowMapping] | RowMapping,
) -> AnnotationMethodLinkAggregate:
    """
    Given a row from the DB containing the results of an aggregate query,
    format the results using the proper GraphQL types.
    """
    aggregate = []
    if type(query_results) is not list:
        query_results = [query_results]  # type: ignore
    for row in query_results:
        aggregate.append(format_annotation_method_link_aggregate_row(row))
    return AnnotationMethodLinkAggregate(aggregate=aggregate)


def format_annotation_method_link_aggregate_row(row: RowMapping) -> AnnotationMethodLinkAggregateFunctions:
    """
    Given a single row from the DB containing the results of an aggregate query,
    format the results using the proper GraphQL types.
    """
    output = AnnotationMethodLinkAggregateFunctions()
    for key, value in row.items():
        # Key is either an aggregate function or a groupby key
        group_keys = key.split(".")
        aggregate = key.split("_", 1)
        if aggregate[0] not in aggregator_map.keys():
            # Turn list of groupby keys into nested objects
            if not output.groupBy:
                output.groupBy = AnnotationMethodLinkGroupByOptions()
            group = build_annotation_method_link_groupby_output(output.groupBy, group_keys, value)
            output.groupBy = group
        else:
            aggregate_name = aggregate[0]
            if aggregate_name == "count":
                output.count = value
            else:
                aggregator_fn, col_name = aggregate[0], aggregate[1]
                if not getattr(output, aggregator_fn):
                    if aggregate_name in ["min", "max"]:
                        setattr(output, aggregator_fn, AnnotationMethodLinkMinMaxColumns())
                    else:
                        setattr(output, aggregator_fn, AnnotationMethodLinkNumericalColumns())
                setattr(getattr(output, aggregator_fn), col_name, value)
    return output


@strawberry.field(extensions=[DependencyExtension()])
async def resolve_annotation_method_links_aggregate(
    info: Info,
    session: AsyncSession = Depends(get_db_session, use_cache=False),
    authz_client: AuthzClient = Depends(get_authz_client),
    principal: Principal = Depends(require_auth_principal),
    where: Optional[AnnotationMethodLinkWhereClause] = None,
    # TODO: add support for groupby, limit/offset
) -> AnnotationMethodLinkAggregate:
    """
    Aggregate values for AnnotationMethodLink objects. Used for queries (see graphql_api/queries.py).
    """
    # Get the selected aggregate functions and columns to operate on, and groupby options if any were provided.
    # TODO: not sure why selected_fields is a list
    selections = info.selected_fields[0].selections[0].selections
    aggregate_selections = [selection for selection in selections if selection.name != "groupBy"]
    groupby_selections = [selection for selection in selections if selection.name == "groupBy"]
    groupby_selections = groupby_selections[0].selections if groupby_selections else []

    if not aggregate_selections:
        raise PlatformicsError("No aggregate functions selected")

    rows = await get_aggregate_db_rows(db.AnnotationMethodLink, session, authz_client, principal, where, aggregate_selections, [], groupby_selections)  # type: ignore
    aggregate_output = format_annotation_method_link_aggregate_output(rows)
    return aggregate_output


@strawberry.mutation(extensions=[DependencyExtension()])
async def create_annotation_method_link(
    input: AnnotationMethodLinkCreateInput,
    session: AsyncSession = Depends(get_db_session, use_cache=False),
    authz_client: AuthzClient = Depends(get_authz_client),
    principal: Principal = Depends(require_auth_principal),
    is_system_user: bool = Depends(is_system_user),
) -> db.AnnotationMethodLink:
    """
    Create a new AnnotationMethodLink object. Used for mutations (see graphql_api/mutations.py).
    """
    validated = AnnotationMethodLinkCreateInputValidator(**input.__dict__)
    params = validated.model_dump()

    # Validate that the user can read all of the entities they're linking to.

    # Validate that the user can read all of the entities they're linking to.
    # Check that annotation relationship is accessible.
    if validated.annotation_id:
        annotation = await get_db_rows(
            db.Annotation,
            session,
            authz_client,
            principal,
            {"id": {"_eq": validated.annotation_id}},
            [],
            AuthzAction.VIEW,
        )
        if not annotation:
            raise PlatformicsError("Unauthorized: annotation does not exist")

    # Save to DB
    params["owner_user_id"] = int(principal.id)
    new_entity = db.AnnotationMethodLink(**params)

    # Are we actually allowed to create this entity?
    if not authz_client.can_create(new_entity, principal):
        raise PlatformicsError("Unauthorized: Cannot create entity")

    session.add(new_entity)
    await session.commit()
    return new_entity


@strawberry.mutation(extensions=[DependencyExtension()])
async def update_annotation_method_link(
    input: AnnotationMethodLinkUpdateInput,
    where: AnnotationMethodLinkWhereClauseMutations,
    session: AsyncSession = Depends(get_db_session, use_cache=False),
    authz_client: AuthzClient = Depends(get_authz_client),
    principal: Principal = Depends(require_auth_principal),
    is_system_user: bool = Depends(is_system_user),
) -> Sequence[db.AnnotationMethodLink]:
    """
    Update AnnotationMethodLink objects. Used for mutations (see graphql_api/mutations.py).
    """
    validated = AnnotationMethodLinkUpdateInputValidator(**input.__dict__)
    params = validated.model_dump()

    # Need at least one thing to update
    num_params = len([x for x in params if params[x] is not None])
    if num_params == 0:
        raise PlatformicsError("No fields to update")

    # Validate that the user can read all of the entities they're linking to.
    # Check that annotation relationship is accessible.
    if validated.annotation_id:
        annotation = await get_db_rows(
            db.Annotation,
            session,
            authz_client,
            principal,
            {"id": {"_eq": validated.annotation_id}},
            [],
            AuthzAction.VIEW,
        )
        if not annotation:
            raise PlatformicsError("Unauthorized: annotation does not exist")
        params["annotation"] = annotation[0]
        del params["annotation_id"]

    # Fetch entities for update, if we have access to them
    entities = await get_db_rows(
        db.AnnotationMethodLink, session, authz_client, principal, where, [], AuthzAction.UPDATE,
    )
    if len(entities) == 0:
        raise PlatformicsError("Unauthorized: Cannot update entities")

    # Update DB
    updated_at = datetime.datetime.now()
    for entity in entities:
        entity.updated_at = updated_at
        for key in params:
            if params[key] is not None:
                setattr(entity, key, params[key])

    if not authz_client.can_update(entity, principal):
        raise PlatformicsError("Unauthorized: Cannot access new collection")

    await session.commit()
    return entities


@strawberry.mutation(extensions=[DependencyExtension()])
async def delete_annotation_method_link(
    where: AnnotationMethodLinkWhereClauseMutations,
    session: AsyncSession = Depends(get_db_session, use_cache=False),
    authz_client: AuthzClient = Depends(get_authz_client),
    principal: Principal = Depends(require_auth_principal),
) -> Sequence[db.AnnotationMethodLink]:
    """
    Delete AnnotationMethodLink objects. Used for mutations (see graphql_api/mutations.py).
    """
    # Fetch entities for deletion, if we have access to them
    entities = await get_db_rows(
        db.AnnotationMethodLink, session, authz_client, principal, where, [], AuthzAction.DELETE,
    )
    if len(entities) == 0:
        raise PlatformicsError("Unauthorized: Cannot delete entities")

    # Update DB
    for entity in entities:
        await session.delete(entity)
    await session.commit()
    return entities
