import re


def slugify(text: str) -> str:
    """Convert text to a slug format suitable for IDs."""
    if not text:
        return "unknown"
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')


def add_annotation_ingest_ids(config: dict) -> None:
    """Add annotation_ingest_id to all annotations that don't have one.

    The annotation_ingest_id is generated by:
    1. Extracting the annotation_object.name
    2. Converting to lowercase and replacing non-alphanumeric chars with hyphens
    3. Appending a counter to ensure uniqueness within the config file

    Example: "cytosolic ribosome" -> "cytosolic-ribosome-1"
    """
    annotations = config.get("annotations")
    if not annotations:
        return

    seen_ids = {}  # Track IDs to ensure uniqueness within file

    for annotation in annotations:
        metadata = annotation.get("metadata")
        if not metadata:
            continue

        # Skip if already has annotation_ingest_id
        if "annotation_ingest_id" in metadata:
            # Track existing ID for uniqueness counter
            existing_id = metadata["annotation_ingest_id"]
            base = re.sub(r'-\d+$', '', existing_id)
            seen_ids[base] = seen_ids.get(base, 0) + 1
            continue

        # Get name from annotation_object
        annotation_object = metadata.get("annotation_object", {})
        obj_name = annotation_object.get("name", "unknown")

        # Generate base ID from name
        base_id = slugify(obj_name)

        # Ensure uniqueness within file by adding counter
        count = seen_ids.get(base_id, 0) + 1
        seen_ids[base_id] = count

        # Add the annotation_ingest_id field
        metadata["annotation_ingest_id"] = f"{base_id}-{count}"


def upgrade(config: dict) -> dict:
    """Upgrade config from version 1.2.0 to 1.3.0.

    Changes:
    - Adds annotation_ingest_id to all annotations for unique identification
    """
    add_annotation_ingest_ids(config)
    config["version"] = "1.3.0"
    return config
