CREATE ROLE hasura_graphql WITH LOGIN PASSWORD 'XxxxxXXX' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO hasura_graphql;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO hasura_graphql;

CREATE SCHEMA IF NOT EXISTS hdb_catalog;
ALTER SCHEMA hdb_catalog OWNER TO hasura_graphql;

ALTER DEFAULT PRIVILEGES IN SCHEMA hdb_catalog GRANT SELECT, INSERT, DELETE ON TABLES TO hasura_graphql;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA hdb_catalog TO hasura_graphql;
GRANT USAGE ON SCHEMA public TO hasura_graphql;
GRANT USAGE ON SCHEMA hdb_catalog TO hasura_graphql;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
