"""
Auto-generated by running `make codegen`. Do not edit!
Make changes to the template platformics/codegen/templates/validators/class_name.py.j2 instead.

Pydantic validator for AnnotationFile
"""

# ruff: noqa: E501 Line too long


import uuid

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from support.enums import annotation_file_source_enum
from typing_extensions import Annotated


class AnnotationFileCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    alignment_id: Annotated[uuid.UUID | None, Field()] = None
    annotation_shape_id: Annotated[uuid.UUID | None, Field()] = None
    tomogram_voxel_spacing_id: Annotated[uuid.UUID | None, Field()] = None
    format: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    s3_path: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    file_size: Annotated[float | None, Field()] = None
    https_path: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    is_visualization_default: Annotated[bool | None, Field()] = None
    source: Annotated[annotation_file_source_enum | None, Field()] = None
    id: Annotated[int, Field()]


class AnnotationFileUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    alignment_id: Annotated[uuid.UUID | None, Field()] = None
    annotation_shape_id: Annotated[uuid.UUID | None, Field()] = None
    tomogram_voxel_spacing_id: Annotated[uuid.UUID | None, Field()] = None
    format: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ] = None
    s3_path: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ] = None
    file_size: Annotated[float | None, Field()] = None
    https_path: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ] = None
    is_visualization_default: Annotated[bool | None, Field()] = None
    source: Annotated[annotation_file_source_enum | None, Field()] = None
    id: Annotated[int | None, Field()] = None
