"""
Pydantic validator for AnnotationShape

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/validators/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


from support.enums import annotation_file_shape_type_enum

import typing
import datetime
import uuid

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from typing_extensions import Annotated


class AnnotationShapeCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    annotation_id: Annotated[uuid.UUID | None, Field()]
    shape_type: Annotated[annotation_file_shape_type_enum | None, Field()]
    id: Annotated[int, Field()]


class AnnotationShapeUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    annotation_id: Annotated[uuid.UUID | None, Field()]
    shape_type: Annotated[annotation_file_shape_type_enum | None, Field()]
    id: Annotated[int | None, Field()]
