"""
Pydantic validator for Owner

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/validators/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


from pydantic import BaseModel, ConfigDict, StringConstraints
from typing_extensions import Annotated


class OwnerCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    name: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]


class OwnerUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    name: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
