"""
Auto-generated by running `make codegen`. Do not edit!
Make changes to the template platformics/codegen/templates/validators/class_name.py.j2 instead.

Pydantic validator for PerSectionParameters
"""

# ruff: noqa: E501 Line too long


import uuid

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated


class PerSectionParametersCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    astigmatic_angle: Annotated[float | None, Field()] = None
    frame_id: Annotated[uuid.UUID, Field()]
    major_defocus: Annotated[float | None, Field()] = None
    max_resolution: Annotated[float | None, Field()] = None
    minor_defocus: Annotated[float | None, Field()] = None
    phase_shift: Annotated[float | None, Field()] = None
    raw_angle: Annotated[float, Field()]
    run_id: Annotated[uuid.UUID, Field()]
    tiltseries_id: Annotated[uuid.UUID, Field()]
    z_index: Annotated[
        int,
        Field(
            ge=0,
        ),
    ]
    id: Annotated[int, Field()]


class PerSectionParametersUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    astigmatic_angle: Annotated[float | None, Field()] = None
    frame_id: Annotated[uuid.UUID | None, Field()] = None
    major_defocus: Annotated[float | None, Field()] = None
    max_resolution: Annotated[float | None, Field()] = None
    minor_defocus: Annotated[float | None, Field()] = None
    phase_shift: Annotated[float | None, Field()] = None
    raw_angle: Annotated[float | None, Field()] = None
    run_id: Annotated[uuid.UUID | None, Field()] = None
    tiltseries_id: Annotated[uuid.UUID | None, Field()] = None
    z_index: Annotated[
        int | None,
        Field(
            ge=0,
        ),
    ] = None
    id: Annotated[int | None, Field()] = None
