"""
Pydantic validator for Sample

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/validators/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import typing
import datetime
import uuid

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from typing_extensions import Annotated


class SampleCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    name: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
            min_length=4,
            max_length=128,
        ),
    ]
    sample_type: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    water_control: Annotated[bool, Field()]
    collection_date: Annotated[datetime.datetime | None, Field()]
    collection_location: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    description: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    system_mutable_field: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    producing_run_id: Annotated[uuid.UUID | None, Field()]
    collection_id: Annotated[
        int,
        Field(
            ge=0,
        ),
    ]
    deleted_at: Annotated[datetime.datetime | None, Field()]


class SampleUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    name: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
            min_length=4,
            max_length=128,
        ),
    ]
    sample_type: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    water_control: Annotated[bool | None, Field()]
    collection_date: Annotated[datetime.datetime | None, Field()]
    collection_location: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    description: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    system_mutable_field: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    collection_id: Annotated[
        int | None,
        Field(
            ge=0,
        ),
    ]
    deleted_at: Annotated[datetime.datetime | None, Field()]
