name: Delete an RDev Stack

on:
  pull_request:
    types: [ unlabeled, closed ]

jobs:
  delete-stack:
    runs-on: ARM64
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'stack') || github.event.pull_request.state == 'closed' }}
    permissions:
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Delete Stack
        uses: chanzuckerberg/argus-artifacts/ci/packages/delete-stack@v0.27.0
        with:
          appName: cryoet-apiv2
          envName: rdev
