name: Validate dataset configs

on:
  push:
    branches:
      - main
    paths:
      - ingestion_tools/dataset_configs/
      - schema/v1.1.0/Makefile
      - schema/v1.1.0/*.yaml
      - schema/v1.1.0/*.py
  pull_request:
    paths:
      - ingestion_tools/dataset_configs/
      - schema/v1.1.0/Makefile
      - schema/v1.1.0/*.yaml
      - schema/v1.1.0/*.py
  workflow_dispatch:

jobs:
  run-validation:
    name: Validate dataset configs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --no-cache-dir poetry
          poetry config virtualenvs.create false
          poetry install
        working-directory: schema/
      - name: Build Pydantic models
        run: make build
        working-directory: schema/v1.1.0
      - name: Validate dataset configs
        run: |
          make validate-configs-with-network
        working-directory: schema/v1.1.0
      - name: Archive validation results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dataset-configs-validation-logs
          path: schema/v1.1.0/dataset_config_validate_errors/
