name: Docker Build Staging/Prod

on:
  push:
    branches:
      - main

jobs:
  argus_builder:
    uses: ./.github/workflows/workflow-argus-docker-build.yaml
    if: github.event.sender.type != 'Bot'
    secrets: inherit
    with:
      envs: staging,prod
      path_filters: '!.infra/**,apiv2/**'
      branches: release-please--branches--main
