name: Docker Build Staging/Prod

on:
  push:
    paths:
    - 'apiv2/**'

jobs:
  argus_builder:
    uses: ./.github/workflows/workflow-argus-docker-build.yaml
    secrets: inherit
    with:
      envs: staging,prod
      path_filters: '!.infra/**,apiv2/**'
      branches_include: release-please--branches--main--components--apiv2
