name: Docker Image Build

on:
  workflow_call:
    inputs:
      envs:
        description: 'Env names, comma delimited'
        required: true
        type: string
      path_filters:
        description: 'Glob patterns to match against changed files in the repository, comma delimited'
        required: true
        type: string
      branches:
        description: 'Branches to build on, comma delimited'
        required: false
        type: string
        default: '*'
      branches_ignore:
        description: 'Branches to skip build on, comma delimited'
        required: false
        type: string
        default: ''

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@c16c1304dd2ad139752511ed3d183a2956bed38b
    secrets: inherit
    with:
      branches: ${{ inputs.branches }}
      branches_ignore: ${{ inputs.branches_ignore }}
      path_filters: ${{ inputs.path_filters }}
      envs: ${{ inputs.envs }}
      images: |
        [
          {
            "name": "apiv2",
            "context": "./apiv2",
            "dockerfile": "apiv2/Dockerfile"
          }
        ]
